### ISSUE TITLE
Issue loading module

### ISSUE THREAD

**Issue by sirBdone** [boeegh/PsChat#2]
what powershell version is required for this module, because it's failing on [http] and [console]. add-type -assemblyname system.web and others required to load, but I can't get past this:
At C:\Program Files\WindowsPowerShell\Modules\PsChat\0.0.27\Classes\Dialog.psm1:8 char:6
+     [ConsoleInput] $ConsoleInput
+      ~~~~~~~~~~~~
Unable to find type [ConsoleInput].
At C:\Program Files\WindowsPowerShell\Modules\PsChat\0.0.27\Classes\Dialog.psm1:9 char:6
+     [ConsoleInputHistory] $ConsoleInputHistory
+      ~~~~~~~~~~~~~~~~~~~
Unable to find type [ConsoleInputHistory].
At C:\Program Files\WindowsPowerShell\Modules\PsChat\0.0.27\Classes\Dialog.psm1:14 
char:31
+         $this.ConsoleInput = [ConsoleInput]::new()
+                               ~~~~~~~~~~~~
Unable to find type [ConsoleInput].
At C:\Program Files\WindowsPowerShell\Modules\PsChat\0.0.27\Classes\Dialog.psm1:15 
char:38
+         $this.ConsoleInputHistory = [ConsoleInputHistory]::new()
+                                      ~~~~~~~~~~~~~~~~~~~
Unable to find type [ConsoleInputHistory].
    + CategoryInfo          : InvalidOperation: (C:\Program File...s\PsChatUi.psm1:Stri 
   ng) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound
 
Import-Module : The module to process 'PsChat.psm1', listed in field 
'ModuleToProcess/RootModule' of module manifest 'C:\Program 
Files\WindowsPowerShell\Modules\PsChat\0.0.27\PsChat.psd1' was not processed because no 
valid module was found in any module directory.
At line:1 char:1
+ Import-Module PsChat -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PsChat:String) [Import-Module], PSI 
   nvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands. 
   ImportModuleCommand

**Comment by suneb** [comment]
Hi @sirBdone - I'll look into it. I've developed it using Powershell-Core, and there seems to be some differences in how callback functions are resolved, that needs to be fixes.

**Comment by suneb** [comment]
Had some problems with the build pipeline after the changes to support Powershell Desktop, however it _should_ work now
